export enum BoardPermission {
  VIEW_BOARD = "VIEW_BOARD",
  UPDATE_BOARD = "UPDATE_BOARD",
  DELETE_BOARD = "DELETE_BOARD",
  MANAGE_MEMBERS = "MANAGE_MEMBERS",
  CREATE_COLUMN = "CREATE_COLUMN",
  UPDATE_COLUMN = "UPDATE_COLUMN",
  DELETE_COLUMN = "DELETE_COLUMN",
  MOVE_COLUMN = "MOVE_COLUMN",
  CREATE_TASK = "CREATE_TASK",
  UPDATE_TASK = "UPDATE_TASK",
  DELETE_TASK = "DELETE_TASK",
  MOVE_TASK = "MOVE_TASK",
}
